BoxLayout:
    orientation: 'vertical'

    BoxLayout:
        orientation: 'horizontal'

        TextInput:
            id: input_number
            text: ''
            size_hint_x: 2

        BoxLayout:
            orientation: 'vertical'

            Button:
                text: 'Up'

            Button:
                text: 'Down'

    Button:
        text: 'Convert m to km'

    Label:
        id: output_label
        text: 'Output'
        color: (1, 1, 0, 1)


